CREATE TABLE "classifieds" (
	"id" uuid PRIMARY KEY NOT NULL,
	"provider" text NOT NULL,
	"notification_type" text,
	"last_webhook_event_id" uuid NOT NULL,
	"last_received_at" timestamp with time zone DEFAULT now() NOT NULL,
	"property_id" uuid NOT NULL,
	"currency" text NOT NULL,
	"square_unit" text NOT NULL,
	"published_at" timestamp with time zone,
	"title" text,
	"description" text,
	"status_current" text NOT NULL,
	"meta_first_seen_at" timestamp with time zone NOT NULL,
	"meta_last_modified_at" timestamp with time zone NOT NULL,
	"meta_last_seen_at" timestamp with time zone NOT NULL,
	"meta_removed_at" timestamp with time zone,
	"source_domain" text NOT NULL,
	"source_url" text NOT NULL,
	"publisher_is_professional" boolean NOT NULL,
	"publisher_type" text,
	"publisher_email" text,
	"publisher_phone" text,
	"publisher_fees_url" text,
	"publisher_siren" text,
	"publisher_siret" text,
	"contact_name" text,
	"contact_email" text,
	"contact_phone" text,
	"location_city_name" text NOT NULL,
	"location_city_insee_code" text NOT NULL,
	"location_country" text NOT NULL,
	"location_department" text NOT NULL,
	"location_postcode" text NOT NULL,
	"location_latitude" double precision,
	"location_longitude" double precision,
	"property_type" text NOT NULL,
	"property_area" real,
	"property_room_count" integer,
	"property_bedroom_count" integer,
	"property_bathroom_count" integer,
	"property_shower_room_count" integer,
	"property_toilet_count" integer,
	"property_floor" integer,
	"property_floor_count" integer,
	"property_construction_year" integer,
	"property_renovation_year" integer,
	"property_balcony_area" real,
	"property_balcony_count" integer,
	"property_terrace_area" real,
	"property_terrace_count" integer,
	"property_land_area" real,
	"property_living_room_area" real,
	"property_orientation" text,
	"property_air_conditioning_exists" boolean,
	"property_alarm_exists" boolean,
	"property_attic_exists" boolean,
	"property_balcony_exists" boolean,
	"property_caretaker_exists" boolean,
	"property_cellar_exists" boolean,
	"property_door_code_exists" boolean,
	"property_elevator_exists" boolean,
	"property_fireplace_exists" boolean,
	"property_garage_exists" boolean,
	"property_garden_exists" boolean,
	"property_intercom_exists" boolean,
	"property_is_condominium" boolean,
	"property_is_disabled_friendly" boolean,
	"property_is_dual_aspect" boolean,
	"property_is_new" boolean,
	"property_is_occupied" boolean,
	"property_parking_exists" boolean,
	"property_renovation_is_needed" boolean,
	"property_swimming_pool_exists" boolean,
	"property_terrace_exists" boolean,
	"property_toilet_separate_exists" boolean,
	"transaction_type" text NOT NULL,
	"transaction_price_current" integer NOT NULL,
	"transaction_price_initial" integer NOT NULL,
	"transaction_price_per_square_unit" integer,
	"energy_dpe_date" date,
	"energy_dpe_label" text,
	"energy_dpe_value" integer,
	"energy_ges_date" date,
	"energy_ges_label" text,
	"energy_ges_value" integer,
	"energy_heating_source" text,
	"energy_heating_system" text,
	"energy_heating_type" text
);
--> statement-breakpoint
ALTER TABLE "classifieds" ADD CONSTRAINT "classifieds_last_webhook_event_id_webhook_events_id_fk" FOREIGN KEY ("last_webhook_event_id") REFERENCES "public"."webhook_events"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "classifieds_property_id_idx" ON "classifieds" USING btree ("property_id");--> statement-breakpoint
CREATE INDEX "classifieds_status_current_idx" ON "classifieds" USING btree ("status_current");--> statement-breakpoint
CREATE INDEX "classifieds_location_department_idx" ON "classifieds" USING btree ("location_department");--> statement-breakpoint
CREATE INDEX "classifieds_last_received_at_idx" ON "classifieds" USING btree ("last_received_at");--> statement-breakpoint
CREATE INDEX "classifieds_last_received_at_id_idx" ON "classifieds" USING btree ("last_received_at","id");--> statement-breakpoint
CREATE INDEX "classifieds_meta_last_seen_at_idx" ON "classifieds" USING btree ("meta_last_seen_at");--> statement-breakpoint
CREATE INDEX "classifieds_last_webhook_event_id_idx" ON "classifieds" USING btree ("last_webhook_event_id");--> statement-breakpoint
CREATE INDEX "classifieds_property_type_transaction_type_idx" ON "classifieds" USING btree ("property_type","transaction_type");--> statement-breakpoint
CREATE INDEX "classifieds_transaction_type_location_department_idx" ON "classifieds" USING btree ("transaction_type","location_department");--> statement-breakpoint
CREATE INDEX "classifieds_transaction_type_property_type_location_department_idx" ON "classifieds" USING btree ("transaction_type","property_type","location_department");--> statement-breakpoint
CREATE INDEX "classifieds_property_id_source_domain_idx" ON "classifieds" USING btree ("property_id","source_domain");--> statement-breakpoint
CREATE INDEX "classifieds_property_id_last_received_at_idx" ON "classifieds" USING btree ("property_id","last_received_at");
